cli:
  image: docker-registry.bringnow.com/bringnow/letsencrypt-manager:latest
  environment:
    - LE_EMAIL=admins@bringnow.com
    - LE_RSA_KEY_SIZE=4096
  volumes:
    - /etc/letsencrypt:/etc/letsencrypt
    - /var/lib/letsencrypt:/var/lib/letsencrypt
    - /var/acme-webroot:/var/acme-webroot

cron:
  image: docker-registry.bringnow.com/bringnow/letsencrypt-manager:latest
  command: cron-auto-renewal
  environment:
    - LE_EMAIL=admins@bringnow.com
    - LE_RSA_KEY_SIZE=4096
  volumes:
    - /etc/letsencrypt:/etc/letsencrypt
    - /var/lib/letsencrypt:/var/lib/letsencrypt
    - /var/acme-webroot:/var/acme-webroot
